name: use_up
description: "Your personal expiry date tracker and inventory manager."
publish_to: 'none'
version: 1.0.3+4
environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # 导航
  go_router: ^13.2.0

  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  intl: ^0.20.2

  # 数据库
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: 2.1.1  # 降级

  # 功能插件 (锁定版本以兼容 SDK 34)
  image_picker: 1.0.4  # 降级
  uuid: ^4.3.3
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  path: ^1.9.0
  url_launcher: 6.2.1  # 降级
  shared_preferences: 2.2.2  # 降级
  flutter_timezone: ^3.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AppIcons/playstore.png"

flutter:
  assets:
    - assets/AppIcons/
  generate: true
  uses-material-design: true
