name: use_up
# 1. 修改描述：不要用默认的 "A new Flutter project."
description: "Your personal expiry date tracker and inventory manager." 

publish_to: 'none'

# 2. 修改版本号：正式上架建议从 1.0.0 开始
# 格式为：主版本.次版本.补丁版本+构建号(versionCode)
# 注意：每次上架 Google Play，'+' 后面的数字必须比上一次大（例如下次是 +2）
version: 1.0.1+2
environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # UI & Design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  intl: ^0.19.0

  # Backend/Data (Local)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  # Features
  # mobile_scanner: ^7.1.4
  image_picker: ^1.0.7
  uuid: ^4.3.3
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  path: ^1.9.0
  
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AppIcons/playstore.png"

flutter:
  assets:
    - assets/AppIcons/

  generate: true

  uses-material-design: true
